### ISSUE TITLE
GTIDSet 有并发安全问题

### ISSUE THREAD

**Issue by nextzhou** [siddontang/go-mysql#339]
接受到 `GTIDEvent` 时会调用 `GTIDSet.Update()` 写 `GTIDSet`,  此时调用 `GTIDSet` 其他方法时会发生读写冲突。
尤其是通过 `Canal.SyncedGTIDSet()` 获取到 `GTIDSet` 后，没有任何手段保证读写该对象是并发安全的(因为 `BinlogSyncer.onStream()` 中在调用 `GTIDSet.Update()`)

**Comment by nextzhou** [comment]
常见场景是定时调用 `Canal.SyncedGTIDSet()` 获取已同步的位置，但读取拿到的 GTIDSet 时由于并发问题可能会拿到中间状态。

**Comment by siddontang** [comment]
PTAL @GregoryIan

**Comment by bytewatch** [comment]
This because  func  `Canal.startSyncer` doesn't pass a copy of `Canal.master.Gset`. 
I think this is a bug, causes not only `Canal.SyncedGTIDSet()` conflict with `BinlogSyncer.parseEvent`. More terrible is : `Canal.master.Gset` is updated earlier than it should, because Canal.master.Gset is updated when `BinlogSyncer.parseEvent` meets a GTID event, but what we want is updated when we receive the whole trx. 
PTAL @siddontang @GregoryIan

**Comment by GregoryIan** [comment]
yep it's a known bug, we would pass a copy of gtid set into BinlogSyncer, I ignore `canal` before, thanks @nextzhou

**Comment by GregoryIan** [comment]
fixed
