### ISSUE TITLE
Why these channels buffered?

### ISSUE THREAD

**Issue by gdey** [siddontang/go-mysql#37]
Is there are reason these channels are buffered?
https://github.com/siddontang/go-mysql/blob/master/replication/binlogstreamer.go#L68-L69

**Comment by siddontang** [comment]
For fetching more binlog at same time. 

No need fetching one, handling one, and loop

**Comment by gdey** [comment]
But, the those events are just sitting on the queue, you still looping, fetching one at a time, the only thing thing that not happening is if the handler is not ready it will fill up the buffer. Also, why 1024 and 4? Trying to get understanding why we are using the buffered channels, there does not seem to be any performance need, but there is a large possibility of data loss occurring as there there no one who has responsibility for the events/error sitting in those message queues.

**Comment by siddontang** [comment]
@gdey 

Yes, in binlog syncer, we are still looping and fetching because we can only sync the binlog one by one(of course, we can use a io buffer to read lots of network data:-) ).
The channel is just for outer use, when you consume the binlog, the syncer can sync new binlog at same time. 
I don' thinkg this can cause the data lose, you only know the binlog sync position when you consume it, so even crashed, you can still resume from the consumed binlog pos, not the read pos in binlog syncer, binlog syncer doesn't save this.  
The  error 4 is a magic time, and I just want to avoid block, but we can use send + default instead.
