### ISSUE TITLE
Can add the pos mysql.Position parameter to EventHandler.OnRow?

### ISSUE THREAD

**Issue by jianjunlu** [siddontang/go-mysql#440]
The information that can be obtained after adding is more complete.

**Comment by jianjunlu** [comment]
I am implementing a data synchronization feature that requires the last location to record data changes, while OnRow does not contain position information.

**Comment by oneslash** [comment]
```go

type RowsEvent struct {
	Table  *schema.Table
	Action string
	// changed row list
	// binlog has three update event version, v0, v1 and v2.
	// for v1 and v2, the rows number must be even.
	// Two rows for one event, format is [before update row, after update row]
	// for update v0, only one row for a event, and we don't support this version.
	Rows [][]interface{}
	// Header can be used to inspect the event
	Header *replication.EventHeader
}
```

replication.EventHeader - has already the `LogPos    uint32` information.

also on OnPosSynced you can get it too, I send it usually to a chan which saves the pos.

```go
// OnPosSynced is called when binlog position is changed
func (h *LegacyDbEventHandler) OnPosSynced(pos mysql.Position, gtid mysql.GTIDSet, b bool) error {
	h.posChan <- pos

	return nil
}
```

**Comment by jianjunlu** [comment]
1. I need to store pos to the database. There is no corresponding binlog file name for pos in Header.

2. The pos in OnPosSynced is the pos of another event, which is not equal to the pos in OnRow.

3. Also, store pos to the database, which triggers OnRow and OnPosSynced, which will cause an infinite loop if in  OnPosSynced store the pos.

**Comment by RainJoe** [comment]
@jianjunlu Have you soloved this problem? We have the same needs to save the pos in OnRow.

**Comment by agorman** [comment]
I have the same issue. After successfully processing an `OnRow` event I'd like to store the next position so that if my application restarts it can start where it left off.

Using the `OnPosSynced` handler is problematic because like @jianjunlu said if I'm saving the position to the same database it causes an infinite loop because it fires every time I save the position. This could be solved if either:

1. `OnRow` returned a `mysql.Position` that stored the next position.
2. `OnPosSynced` followed `IncludeTableRegex` and `ExcludeTableRegex` (it would be nice if all callbacks did this).

If there is better way to save the position after successfully handling an `OnRow` event I'd be happy to use it.

@jianjunlu @RainJoe did you guys have a work around for this issue?
